name: Deploy Container

# Déclenche l’action à chaque push sur la branche main
on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1️⃣ Récupérer le code du repo
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2️⃣ Build Docker image et push sur DockerHub
    - name: Build and Push Docker image
      run: |
        echo "Building Docker image..."
        docker build -t iyedmh/monitor:latest ./docker
        echo "Logging in to DockerHub..."
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Pushing Docker image to DockerHub..."
        docker push iyedmh/monitor:latest

    # 3️⃣ Appliquer Terraform pour créer la VM cloud
    - name: Terraform Apply
      uses: hashicorp/terraform-github-actions@v1
      with:
        tf_actions_version: latest
        working-directory: ./terraform
        command: apply
        auto-approve: true
